### ISSUE TITLE
Chiron with firmware 1.3.5, new LCD supported?

### ISSUE THREAD

**Issue by gaby64** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#10]
Is the new LCD of newer Chiron shipped with firmware 1.3.5 supported on this git?

**Comment by dkoch83** [comment]
no

**Comment by raindancer2204** [comment]
**Hi there,**

I have just compiled the dkoch83 github firmware and got it running on my Chiron.

I have the following display that should correspond to the new version right?

Attached is the picture for testing.

Regards Raini

![anycubic_chiron_display](https://user-images.githubusercontent.com/49243048/103685450-87aa4c80-4f8d-11eb-8ecf-0d30a6ee894a.jpg)

**Comment by illuminati05** [comment]
> **Hi there,**
> 
> I have just compiled the dkoch83 github firmware and got it running on my Chiron.
> 
> I have the following display that should correspond to the new version right?
> 
> Attached is the picture for testing.
> 
> Regards Raini
> 
> ![anycubic_chiron_display](https://user-images.githubusercontent.com/49243048/103685450-87aa4c80-4f8d-11eb-8ecf-0d30a6ee894a.jpg)

This display is the old version my friend. They changed some communication from the display to the board.

**Comment by illuminati05** [comment]
![Screenshot_20210316_140853](https://user-images.githubusercontent.com/13906936/111453831-49ab7080-8714-11eb-8cba-78ccef4ffa80.jpg)
![Screenshot_20210316_140827](https://user-images.githubusercontent.com/13906936/111453833-4adc9d80-8714-11eb-8645-7479778d8b46.jpg)

**Comment by illuminati05** [comment]
One way to find out is to check the communication strings in the serial monitor with editing the dkoch83 code

**Comment by illuminati05** [comment]
http://user.support.anycubic.com/Attachs/Uploads/20210317/1615970032285954ea9293ae3e.zip

**Comment by illuminati05** [comment]
Hey guys good news. I have fixed the problem with autoleveling with the new display (V0.0.2) dark edition. Auto levelling menu will not be shwon and executed on the display. I have disassembled the display and connted the serial connector from the display to a serial adapter. The only difference in the communication is that the strings send from the display has changed. Under chiron_lcd.cpp there are these string (A30, A23, ....). The new communication string for auto levelling has changed from "A30" (OLD DISPLAY) to "A36" (NEW DISPLAY). I just added the same code for "A30" at the end of the select case for "A36"

Code:

`//--------------------------------------------------------------------------
    case 36: // A36 auto leveling - NEW TOUCH DISPLAY (V0.0.2 - 1.3.5) #17.03.21
      #ifdef AUTO_BED_LEVELING_BILINEAR
      if( (planner.movesplanned()) || (card.sdprinting) ) {
        write_to_lcd_P(PSTR("J24\r\n"));  // forbid auto leveling
        } else {
        write_to_lcd_P(PSTR("J26\r\n"));  // start auto leveling
      }
      if(TFTcode_seen(TFTcmdbuffer, 'S') ) {
        enqueue_and_echo_commands_P(PSTR("G28\nG29"));
      }
      #else
      write_to_lcd_P(PSTR("J24\r\n"));  // forbid auto leveling
      #endif
    break;
    //--------------------------------------------------------------------------`

Just add this code after:

`case 34: // A34 bed grid write`

My printer now works withe the NEW display like the OLD display. I hope this helps :)

**Comment by dkoch83** [comment]
Thank you, for fix the problem.
i have add the code to the repository

**Comment by illuminati05** [comment]
Hey Thank you for your reply. It seems to be the only change for the display. I haven't found any other change. I will give you feedback if any other things occur. Best regardsDominik-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.03.21, 14:46 schrieb dkoch83 ***@***.***>:

   
  Thank you, for fix the problem. i have add the code to the repository

**Comment by illuminati05** [comment]
My excel sheet with differencesBest regards Dominik-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.03.21, 14:46 schrieb dkoch83 ***@***.***>:

   
  Thank you, for fix the problem. i have add the code to the repository
