### ISSUE TITLE
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER causes errors

### ISSUE THREAD

**Issue by illuminati05** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#12]
Hey dkoch83. The Anycubic Chiron firmware is based on the 1.1.9 version. My anycubic chiron touch display is defect. A new one is not  available. In the configuration.h there is the option for #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER. When I uncomment this i get a lot of compilling errors. This would be fine if an alternative display can be integrated if the stock one (ugly thing) is defect. I have three 12864 display for replacement.

Thanks for your work
Errors

`
sketch\Marlin_main.cpp: In function 'bool ensure_safe_temperature(AdvancedPauseMode)':

Marlin_main.cpp:6964:7: error: 'lcd_advanced_pause_show_message' was not declared in this scope

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_WAIT_FOR_NOZZLES_TO_HEAT, mode);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:6964:7: note: suggested alternative: 'advanced_pause_menu_response'

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_WAIT_FOR_NOZZLES_TO_HEAT, mode);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

       advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'bool load_filament(const float&, const float&, const float&, int8_t, bool, bool, AdvancedPauseMode)':

Marlin_main.cpp:7000:11: error: 'lcd_advanced_pause_show_message' was not declared in this scope

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7000:11: note: suggested alternative: 'advanced_pause_menu_response'

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

           advanced_pause_menu_response

Marlin_main.cpp:7009:11: error: 'lcd_advanced_pause_show_message' was not declared in this scope

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INSERT, mode);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7009:11: note: suggested alternative: 'advanced_pause_menu_response'

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INSERT, mode);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

           advanced_pause_menu_response

Marlin_main.cpp:7033:9: error: 'lcd_advanced_pause_show_message' was not declared in this scope

         lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_LOAD, mode);

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7033:9: note: suggested alternative: 'advanced_pause_menu_response'

         lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_LOAD, mode);

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

         advanced_pause_menu_response

Marlin_main.cpp:7072:15: error: 'lcd_advanced_pause_show_message' was not declared in this scope

               lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_PURGE, mode);

               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7072:15: note: suggested alternative: 'advanced_pause_menu_response'

               lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_PURGE, mode);

               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

               advanced_pause_menu_response

Marlin_main.cpp:7084:13: error: 'lcd_advanced_pause_show_message' was not declared in this scope

             lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_OPTION, mode);

             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7084:13: note: suggested alternative: 'advanced_pause_menu_response'

             lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_OPTION, mode);

             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

             advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'bool unload_filament(const float&, bool, AdvancedPauseMode)':

Marlin_main.cpp:7120:11: error: 'lcd_advanced_pause_show_message' was not declared in this scope

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7120:11: note: suggested alternative: 'advanced_pause_menu_response'

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

           advanced_pause_menu_response

Marlin_main.cpp:7130:9: error: 'lcd_advanced_pause_show_message' was not declared in this scope

         lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_UNLOAD, mode);

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7130:9: note: suggested alternative: 'advanced_pause_menu_response'

         lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_UNLOAD, mode);

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

         advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'bool pause_print(const float&, const point_t&, const float&, bool)':

Marlin_main.cpp:7189:11: error: 'lcd_advanced_pause_show_message' was not declared in this scope

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7189:11: note: suggested alternative: 'advanced_pause_menu_response'

           lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_STATUS);

           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

           advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'void wait_for_filament_reload(int8_t)':

Marlin_main.cpp:7240:7: error: 'lcd_advanced_pause_show_message' was not declared in this scope

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INSERT);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7240:7: note: suggested alternative: 'advanced_pause_menu_response'

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INSERT);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

       advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'void resume_print(const float&, const float&, const float&, int8_t)':

Marlin_main.cpp:7357:7: error: 'lcd_advanced_pause_show_message' was not declared in this scope

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_RESUME);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:7357:7: note: suggested alternative: 'advanced_pause_menu_response'

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_RESUME);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

       advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'void gcode_M105()':

Marlin_main.cpp:8298:24: error: 'UsbOnLineFlag' was not declared in this scope

   if(!card.sdprinting) UsbOnLineFlag = true; // if reveive m105 from pc,meant usb on line

                        ^~~~~~~~~~~~~

sketch\Marlin_main.cpp: In function 'void gcode_M109()':

Marlin_main.cpp:8633:2: error: 'write_to_lcd_P' was not declared in this scope

  write_to_lcd_P(PSTR("J07\r\n"));   //hotend heating done

  ^~~~~~~~~~~~~~

sketch\Marlin_main.cpp:8633:2: note: suggested alternative: 'wants_to_cool'

  write_to_lcd_P(PSTR("J07\r\n"));   //hotend heating done

  ^~~~~~~~~~~~~~

  wants_to_cool

Marlin_main.cpp:8637:10: error: 'USBConnectFlag' was not declared in this scope

  else if(USBConnectFlag) {

          ^~~~~~~~~~~~~~

sketch\Marlin_main.cpp:8637:10: note: suggested alternative: 'BlockFlag'

  else if(USBConnectFlag) {

          ^~~~~~~~~~~~~~

          BlockFlag

In file included from sketch\MarlinConfig.h:27:0,

                 from sketch\Marlin.h:35,

                 from sketch\Marlin_main.cpp:259:

sketch\Marlin_main.cpp: In function 'void gcode_M145()':

Marlin_main.cpp:8920:27: error: 'lcd_preheat_hotend_temp' was not declared in this scope

     if (material >= COUNT(lcd_preheat_hotend_temp)) {

                           ^

sketch\macros.h:123:26: note: in definition of macro 'COUNT'

 #define COUNT(a) (sizeof(a)/sizeof(*a))

                          ^

Marlin_main.cpp:8932:9: error: 'lcd_preheat_fan_speed' was not declared in this scope

         lcd_preheat_fan_speed[material] = constrain(v, 0, 255);

         ^~~~~~~~~~~~~~~~~~~~~

Marlin_main.cpp:8937:11: error: 'lcd_preheat_bed_temp' was not declared in this scope

           lcd_preheat_bed_temp[material] = constrain(v, BED_MINTEMP, BED_MAXTEMP - 15);

           ^~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:8937:11: note: suggested alternative: 'lcd_reset_status'

           lcd_preheat_bed_temp[material] = constrain(v, BED_MINTEMP, BED_MAXTEMP - 15);

           ^~~~~~~~~~~~~~~~~~~~

           lcd_reset_status

sketch\Marlin_main.cpp: In function 'void gcode_M851()':

Marlin_main.cpp:11012:3: error: 'SAVE_zprobe_zoffset' was not declared in this scope

   SAVE_zprobe_zoffset = zprobe_zoffset;

   ^~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:11012:3: note: suggested alternative: 'zprobe_zoffset'

   SAVE_zprobe_zoffset = zprobe_zoffset;

   ^~~~~~~~~~~~~~~~~~~

   zprobe_zoffset

sketch\Marlin_main.cpp: In function 'void gcode_M600()':

Marlin_main.cpp:11142:7: error: 'lcd_advanced_pause_show_message' was not declared in this scope

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INIT, ADVANCED_PAUSE_MODE_PAUSE_PRINT, target_extruder);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\Marlin_main.cpp:11142:7: note: suggested alternative: 'advanced_pause_menu_response'

       lcd_advanced_pause_show_message(ADVANCED_PAUSE_MESSAGE_INIT, ADVANCED_PAUSE_MODE_PAUSE_PRINT, target_extruder);

       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

       advanced_pause_menu_response

sketch\Marlin_main.cpp: In function 'void kill(const char*)':

Marlin_main.cpp:15213:5: error: 'kill_screen' was not declared in this scope

     kill_screen(lcd_msg);

     ^~~~~~~~~~~

exit status 1
'lcd_advanced_pause_show_message' was not declared in this scope`

**Comment by illuminati05** [comment]
Ich bau gerade ne offizielle marlin 1.1.9 so um das die änderungen von dkoch83 drinnen sind, aber ohne chiron lcd. Dh man kann bei dieser variante ein normales 12864 anhängen. Pins muss ich noch prüfen. Kompilieren geht schon

**Comment by illuminati05** [comment]
Und dh die anycubic adapter müssen weg...

**Comment by illuminati05** [comment]
Thats a pitty that no one responses

**Comment by dkoch83** [comment]
Sorry for the late answer,
I look not so often at the projetct.
I have rebuild my chiron with an BTT SKR 1.4 Turbo and  TFT35 V2.0 Touch Screen from BTT. 
At the moment i use the newest version of Marlin firmware. 

This firmware here is only for the Chiron with the original display. 

The chiron Display controllse the chiron board via serial comunication ,his owne commands and respons. therfor it was required to add some code to the orginal marlin firmware to handle the display.
And this code modifikation makes it imporsible to compile the firmware hear with other displays.  


You cann config a new version or a fresh version of the 1.1.9 of marlin firmware for the chiron board with your display but this cann take a lot of time.

**Comment by dkoch83** [comment]
Entschuldigung für die späte Antwort,
Ich schaue nicht so oft auf das Projekt.
Ich habe mein Chiron mit einem BTT SKR 1.4 Turbo und einem TFT35 V2.0 Touchscreen von BTT umgebaut.
Im Moment benutze ich die neueste Version der Marlin Firmware.

Diese Firmware hier ist nur für den Chiron mit dem Original-Display.

Das Chiron-Display steuert das Chiron-Board über die serielle Kommunikation, seine eigenen Befehle und Antworten. Daher musste der ursprünglichen Marlin-Firmware Code hinzugefügt werden, um die Anzeige zu handhaben.
Und diese Code-Änderung macht es unmöglich, die Firmware mit anderen Displays zu kompilieren.


Sie können mit Ihrem Display eine neue Version oder eine neue Version der Marlin-Firmware 1.1.9 für das Chiron-Board konfigurieren, dies kann jedoch viel Zeit in Anspruch nehmen.

**Comment by illuminati05** [comment]
Hey thanks for your answer. In the meantime i have taken an default 1.1.9 and copied the chiron code from you without the display and it compiles with the lcd 12864. So problem solved.
