### ISSUE TITLE
TMC 2208 with linear advance and stelathcop stops extruder motor during print

### ISSUE THREAD

**Issue by illuminati05** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#16]
Since 2 weeks i have enabled the linear advance feature for getting better print corners, but in longer prints or if many edges are print the extruder motor shuts down and the gear can be turned with hand. Board: Trigorilla. This problem is already known also in the marlin 2.0 and lower versions. It looks like that the stepper driver shuts down (because of too much extrude and retractions causes by lin adv) and a restart of the print reenables the extruder motor.

[https://github.com/MarlinFirmware/Marlin/issues/11825](url)

Different people in different forums describes the same problem with LinAdv and they are using an tmc2208 step/dir or UART. My TMC2208 are used as step/dir. To solve the problem the extruder driver must be switched to TMC2209 (it looks like that this issue relsoved in firmware) or to another driver (A4988 or drv8825 or like that) OR DEACTIVATE LIN_ADV (Values = 0). I dont want to loose the high resolution of the steps from TMC2208 with extecellent print corner (no overextrusion) in comparison to A4988 or DRV8825. Addiotionally the main problem is that the Titan extruder from the stock Chiron has an ration of 3:1 (or 4:1). So this is the big problem: Too many steps (high resolution) for the same 1 mm in comaprison to an direct extruder and this causes (it looks like) that the driver shuts down.

Print speed E: 50mm/s
Travel speed X/Y: 100mm/s
Travel speed Z max: 20mm/s
LIN_ADV = 0.2 (tested from 0.1 to 1.0) doesnt matter (0 is working)
Retraction disabled
Coasting disabled
Yerk is default from your code

So my question to you dkoch83: Is it possible to use an TMC2209 in STEP/DIR mode in your configuration?

Best regards

Dominik

**Comment by dkoch83** [comment]
No Problem,
I useed the LV8729 (https://wiki.fysetc.com/LV8729_V1.0/) with the pin MS1 MS2 cut off (1/16 Step) for the extruder

Greatings 
dkoch83
