### ISSUE TITLE
Maximum possible temperature in Configuration.h is reduced by 15 degress in temperature.h 

### ISSUE THREAD

**Issue by illuminati05** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#17]
Hello ladies

Yesterday i was trying to print with abs and petg. So i set my printing temperature to 250°C but my printer on the screen or Repetier Host reduces the value i set to 235°C. So i tried to dismount my anycubic touch screen, because i thought the screen has a limit inside. This did not work. So the code must be the problem. After searching the full code i found the code line where the maximum temperature will be reduced by 15°. I removed the "-15" and now it works. Now it's possible to set the temperature which is set under configuration.h

Configuration.h:362 --> My value is 250 instead of 265 !!!
`#define HEATER_0_MAXTEMP 250`

'-----------------------------------------------------------------------------------------
OLD 
temperature.h:417
`target_temperature[HOTEND_INDEX] = MIN(celsius, maxttemp[HOTEND_INDEX] - 15);`

NEW 
temperature.h:417
`target_temperature[HOTEND_INDEX] = MIN(celsius, maxttemp[HOTEND_INDEX]);`
'-----------------------------------------------------------------------------------------

'-----------------------------------------------------------------------------------------
OLD 
temperature.h:452
`MIN(celsius, BED_MAXTEMP - 15)`

NEW 
temperature.h:452
`MIN(celsius, BED_MAXTEMP)`
'-----------------------------------------------------------------------------------------

Hey dkoch83 

Why is this maximum temperature reduced? The maximum possible temperature is already configurated under Configuration.h
This is a little bit confusing because in the touch lcd a value i think from 260 can be selected (I'm not quite sure)

Best regards

Waidhofer Dominik

**Comment by dkoch83** [comment]
I don't know.
You must ask the marlin firmware programmers.
They did wrote the code.
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/temperature.h#L417
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/temperature.h#L452

Best regards

dkoch83
