### ISSUE TITLE
Pin layout for tmc2208 UART

### ISSUE THREAD

**Issue by Laurens95** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#2]
Hello, 

I am trying to set up the Chiron using tmc2208 stepper drivers (5x) connected by UART. I am having some trouble getting the pins correct. Can you help me getting a good list? If im correct I have to set it in pins_RAMPS_Chiron.h. 
 #define X_SERIAL_TX_PIN    -1
  #define X_SERIAL_RX_PIN    -1
  #define X2_SERIAL_TX_PIN   -1
  #define X2_SERIAL_RX_PIN   -1

  #define Y_SERIAL_TX_PIN    -1
  #define Y_SERIAL_RX_PIN    -1
  #define Y2_SERIAL_TX_PIN   -1
  #define Y2_SERIAL_RX_PIN   -1

  #define Z_SERIAL_TX_PIN    -1
  #define Z_SERIAL_RX_PIN    -1
  #define Z2_SERIAL_TX_PIN   -1
  #define Z2_SERIAL_RX_PIN   -1

  #define E0_SERIAL_TX_PIN   -1
  #define E0_SERIAL_RX_PIN   -1
  #define E1_SERIAL_TX_PIN   -1
  #define E1_SERIAL_RX_PIN   -1
  #define E2_SERIAL_TX_PIN   -1
  #define E2_SERIAL_RX_PIN   -1
  #define E3_SERIAL_TX_PIN   -1
  #define E3_SERIAL_RX_PIN   -1
  #define E4_SERIAL_TX_PIN   -1
  #define E4_SERIAL_RX_PIN   -1

I need X,Y,Z,Z2 and E0.

Laurens

**Comment by dkoch83** [comment]
https://www.3d-druck-community.de/showthread.php?tid=21810
