### ISSUE TITLE
Z homin is not working like in original anycubic firmware

### ISSUE THREAD

**Issue by illuminati05** [dkoch83/Marlin-1.1.9_Anycubic_Chiron#8]
Hey dkoch83

I have installed your version on my Anycubic Chiron. In the default marlin version 1.1.0 (Anycubic 1.3.0) the z homing was different.

Anycubic: 
Z-Homing to the endstops (optical) and after that the z axis moves more down (~3mm).

Your version:
In your version the movement stops directly if the endstop input is coming. So the Z axis is about 3mm above the leveled bed. Is this normal or can i change the way in the config. 

Best regards Waidhofer Dominik

**Comment by dkoch83** [comment]
This can happen. have you level your bed after update the firmware ?
see [readme.md](https://github.com/dkoch83/Marlin-1.1.9_Anycubic_Chiron/blob/master/README.md) (M1000) (Bed Leveling).
Use M1000 bevor do a manuel leveling follow the steps in [readme.md](https://github.com/dkoch83/Marlin-1.1.9_Anycubic_Chiron/blob/master/README.md)

Best regards dkoch83
